### ISSUE TITLE
Panic in reconciler

### ISSUE THREAD

**Issue by DeluxeOwl** [alexandrevilain/temporal-operator#409]
```
2023-07-05T09:28:23Z    INFO    controller-runtime.metrics    Metrics server is starting to listen    {"addr": ":8080"}
2023-07-05T09:28:23Z    INFO    setup    Found cert-manager installation in the cluster, features requiring cert-manager are enabled
2023-07-05T09:28:23Z    INFO    setup    Unable to find istio installation in the cluster, features requiring istio are disabled
2023-07-05T09:28:23Z    INFO    setup    Found prometheus operator installation in the cluster, features requiring prometheus operator are enabled
2023-07-05T09:28:23Z    INFO    controller-runtime.builder    Registering a mutating webhook    {"GVK": "temporal.io/v1beta1, Kind=TemporalCluster", "path": "/mutate-temporal-io-v1beta1-temporalcluster"}
2023-07-05T09:28:23Z    INFO    controller-runtime.webhook    Registering webhook    {"path": "/mutate-temporal-io-v1beta1-temporalcluster"}
2023-07-05T09:28:23Z    INFO    controller-runtime.builder    Registering a validating webhook    {"GVK": "temporal.io/v1beta1, Kind=TemporalCluster", "path": "/validate-temporal-io-v1beta1-temporalcluster"}
2023-07-05T09:28:23Z    INFO    controller-runtime.webhook    Registering webhook    {"path": "/validate-temporal-io-v1beta1-temporalcluster"}
2023-07-05T09:28:23Z    INFO    controller-runtime.builder    Registering a mutating webhook    {"GVK": "temporal.io/v1beta1, Kind=TemporalWorkerProcess", "path": "/mutate-temporal-io-v1beta1-temporalworkerprocess"}
2023-07-05T09:28:23Z    INFO    controller-runtime.webhook    Registering webhook    {"path": "/mutate-temporal-io-v1beta1-temporalworkerprocess"}
2023-07-05T09:28:23Z    INFO    controller-runtime.builder    Registering a validating webhook    {"GVK": "temporal.io/v1beta1, Kind=TemporalWorkerProcess", "path": "/validate-temporal-io-v1beta1-temporalworkerprocess"}
2023-07-05T09:28:23Z    INFO    controller-runtime.webhook    Registering webhook    {"path": "/validate-temporal-io-v1beta1-temporalworkerprocess"}
2023-07-05T09:28:23Z    INFO    setup    starting manager
2023-07-05T09:28:23Z    INFO    controller-runtime.webhook.webhooks    Starting webhook server
2023-07-05T09:28:23Z    INFO    controller-runtime.certwatcher    Updated current TLS certificate
2023-07-05T09:28:23Z    INFO    Starting server    {"path": "/metrics", "kind": "metrics", "addr": ":8080"}
2023-07-05T09:28:23Z    INFO    controller-runtime.webhook    Serving webhook server    {"host": "", "port": 9443}
2023-07-05T09:28:23Z    INFO    Starting server    {"kind": "health probe", "addr": ":8081"}
2023-07-05T09:28:23Z    INFO    controller-runtime.certwatcher    Starting certificate watcher
I0705 09:28:23.993985       1 leaderelection.go:248] attempting to acquire leader lease temporal-system/0cfcfa11.temporal.io...
I0705 09:28:40.766997       1 leaderelection.go:258] successfully acquired lease temporal-system/0cfcfa11.temporal.io
2023-07-05T09:28:40Z    INFO    Starting EventSource    {"controller": "temporalcluster", "controllerGroup": "temporal.io", "controllerKind": "TemporalCluster", "source": "kind source: *v1beta1.TemporalCluster"}
2023-07-05T09:28:40Z    INFO    Starting EventSource    {"controller": "temporalcluster", "controllerGroup": "temporal.io", "controllerKind": "TemporalCluster", "source": "kind source: *v1.Deployment"}
2023-07-05T09:28:40Z    INFO    Starting EventSource    {"controller": "temporalcluster", "controllerGroup": "temporal.io", "controllerKind": "TemporalCluster", "source": "kind source: *v1.ConfigMap"}
2023-07-05T09:28:40Z    INFO    Starting EventSource    {"controller": "temporalcluster", "controllerGroup": "temporal.io", "controllerKind": "TemporalCluster", "source": "kind source: *v1.Service"}
2023-07-05T09:28:40Z    INFO    Starting EventSource    {"controller": "temporalcluster", "controllerGroup": "temporal.io", "controllerKind": "TemporalCluster", "source": "kind source: *v1.ServiceAccount"}
2023-07-05T09:28:40Z    INFO    Starting EventSource    {"controller": "temporalcluster", "controllerGroup": "temporal.io", "controllerKind": "TemporalCluster", "source": "kind source: *v1.Ingress"}
2023-07-05T09:28:40Z    INFO    Starting EventSource    {"controller": "temporalcluster", "controllerGroup": "temporal.io", "controllerKind": "TemporalCluster", "source": "kind source: *v1.Job"}
2023-07-05T09:28:40Z    INFO    Starting EventSource    {"controller": "temporalcluster", "controllerGroup": "temporal.io", "controllerKind": "TemporalCluster", "source": "kind source: *v1.Issuer"}
2023-07-05T09:28:40Z    INFO    Starting EventSource    {"controller": "temporalcluster", "controllerGroup": "temporal.io", "controllerKind": "TemporalCluster", "source": "kind source: *v1.Certificate"}
2023-07-05T09:28:40Z    INFO    Starting EventSource    {"controller": "temporalcluster", "controllerGroup": "temporal.io", "controllerKind": "TemporalCluster", "source": "kind source: *v1.ServiceMonitor"}
2023-07-05T09:28:40Z    INFO    Starting Controller    {"controller": "temporalcluster", "controllerGroup": "temporal.io", "controllerKind": "TemporalCluster"}
2023-07-05T09:28:40Z    DEBUG    events    temporal-operator-controller-manager-66d6577656-zf8gq_8536e5fc-4908-48f6-b331-bd7ba1a86693 became leader    {"type": "Normal", "object": {"kind":"Lease","namespace":"temporal-system","name":"0cfcfa11.temporal.io","uid":"3095bf29-99a2-4e35-a661-23570091dab4","apiVersion":"coordination.k8s.io/v1","resourceVersion":"143108137"}, "reason": "LeaderElection"}
2023-07-05T09:28:40Z    INFO    Starting EventSource    {"controller": "temporalclusterclient", "controllerGroup": "temporal.io", "controllerKind": "TemporalClusterClient", "source": "kind source: *v1beta1.TemporalClusterClient"}
2023-07-05T09:28:40Z    INFO    Starting EventSource    {"controller": "temporalclusterclient", "controllerGroup": "temporal.io", "controllerKind": "TemporalClusterClient", "source": "kind source: *v1.Issuer"}
2023-07-05T09:28:40Z    INFO    Starting EventSource    {"controller": "temporalclusterclient", "controllerGroup": "temporal.io", "controllerKind": "TemporalClusterClient", "source": "kind source: *v1.Certificate"}
2023-07-05T09:28:40Z    INFO    Starting EventSource    {"controller": "temporalclusterclient", "controllerGroup": "temporal.io", "controllerKind": "TemporalClusterClient", "source": "kind source: *v1.Secret"}
2023-07-05T09:28:40Z    INFO    Starting Controller    {"controller": "temporalclusterclient", "controllerGroup": "temporal.io", "controllerKind": "TemporalClusterClient"}
2023-07-05T09:28:40Z    INFO    Starting EventSource    {"controller": "temporalworkerprocess", "controllerGroup": "temporal.io", "controllerKind": "TemporalWorkerProcess", "source": "kind source: *v1beta1.TemporalWorkerProcess"}
2023-07-05T09:28:40Z    INFO    Starting EventSource    {"controller": "temporalworkerprocess", "controllerGroup": "temporal.io", "controllerKind": "TemporalWorkerProcess", "source": "kind source: *v1.Deployment"}
2023-07-05T09:28:40Z    INFO    Starting Controller    {"controller": "temporalworkerprocess", "controllerGroup": "temporal.io", "controllerKind": "TemporalWorkerProcess"}
2023-07-05T09:28:40Z    INFO    Starting EventSource    {"controller": "temporalnamespace", "controllerGroup": "temporal.io", "controllerKind": "TemporalNamespace", "source": "kind source: *v1beta1.TemporalNamespace"}
2023-07-05T09:28:40Z    INFO    Starting Controller    {"controller": "temporalnamespace", "controllerGroup": "temporal.io", "controllerKind": "TemporalNamespace"}
2023-07-05T09:28:41Z    INFO    Starting workers    {"controller": "temporalclusterclient", "controllerGroup": "temporal.io", "controllerKind": "TemporalClusterClient", "worker count": 1}
2023-07-05T09:28:41Z    INFO    Starting workers    {"controller": "temporalnamespace", "controllerGroup": "temporal.io", "controllerKind": "TemporalNamespace", "worker count": 1}
2023-07-05T09:28:41Z    INFO    Starting workers    {"controller": "temporalworkerprocess", "controllerGroup": "temporal.io", "controllerKind": "TemporalWorkerProcess", "worker count": 1}
2023-07-05T09:28:41Z    INFO    Starting workers    {"controller": "temporalcluster", "controllerGroup": "temporal.io", "controllerKind": "TemporalCluster", "worker count": 1}
2023-07-05T09:28:41Z    INFO    Starting reconciliation    {"controller": "temporalcluster", "controllerGroup": "temporal.io", "controllerKind": "TemporalCluster", "TemporalCluster": {"name":"temporal-cluster","namespace":"dgt-system"}, "namespace": "dgt-system", "name": "temporal-cluster", "reconcileID": "1cd7bde1-e8a5-4d6a-ab24-b4bdf831d8b4"}
2023-07-05T09:28:41Z    INFO    Starting reconciliation    {"controller": "temporalnamespace", "controllerGroup": "temporal.io", "controllerKind": "TemporalNamespace", "TemporalNamespace": {"name":"default","namespace":"dgt-system"}, "namespace": "dgt-system", "name": "default", "reconcileID": "ed7d8ea7-052a-41fb-9a30-68aca1780ed2"}
2023-07-05T09:28:41Z    INFO    Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference    {"controller": "temporalnamespace", "controllerGroup": "temporal.io", "controllerKind": "TemporalNamespace", "TemporalNamespace": {"name":"default","namespace":"dgt-system"}, "namespace": "dgt-system", "name": "default", "reconcileID": "ed7d8ea7-052a-41fb-9a30-68aca1780ed2"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
    panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x15278ac]

goroutine 529 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:119 +0x1fa
panic({0x201a0e0, 0x3aaef30})
    /usr/local/go/src/runtime/panic.go:884 +0x212
github.com/alexandrevilain/temporal-operator/api/v1beta1.(*TemporalCluster).GetPublicClientAddress(0xc000fc6000)
    /workspace/api/v1beta1/temporalcluster_types.go:838 +0x10c
github.com/alexandrevilain/temporal-operator/pkg/temporal.buildClusterClientOptions({_, _}, {_, _}, _, {_, _, _})
    /workspace/pkg/temporal/client.go:95 +0x97
github.com/alexandrevilain/temporal-operator/pkg/temporal.GetClusterNamespaceClient({0x2881618, 0xc000af4a50}, {0x288c108?, 0xc00044a660?}, 0x2881618?, {0x0?, 0xc0004ef480?, 0x0?})
    /workspace/pkg/temporal/client.go:148 +0x85
github.com/alexandrevilain/temporal-operator/controllers.(*TemporalNamespaceReconciler).Reconcile(0xc0005bd278, {0x2881618, 0xc000af4a50}, {{{0xc0004ef480?, 0x10?}, {0xc0004ef470?, 0x40da87?}}})
    /workspace/controllers/temporalnamespace_controller.go:107 +0x448
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x2881618?, {0x2881618?, 0xc000af4a50?}, {{{0xc0004ef480?, 0x1f710a0?}, {0xc0004ef470?, 0x0?}}})
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:122 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0002d00a0, {0x2881570, 0xc00080c1c0}, {0x20babe0?, 0xc000050280?})
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:323 +0x3a5
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0002d00a0, {0x2881570, 0xc00080c1c0})
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:274 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:235 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:231 +0x333
Stream closed EOF for temporal-system/temporal-operator-controller-manager-66d6577656-zf8gq (manager)

```

**Comment by alexandrevilain** [comment]
Hi @DeluxeOwl !

Thanks for the issue. Could you please give me more context ? Like your manifests, temporal operator version ...

**Comment by DeluxeOwl** [comment]
Hi,

Apologies for not providing more info. It's the latest release ([v0.13.2](https://github.com/alexandrevilain/temporal-operator/releases/tag/v0.13.2) with cert manager `1.10.1` I believe). I'm running on EKS 1.24, eks.7

It happens after I create the namespace + cluster:
```yaml
apiVersion: temporal.io/v1beta1
kind: TemporalNamespace
metadata:
  name: default
  namespace: dgt-system
spec:
  clusterRef:
    name: temporal-cluster
  description: Default namespace
  retentionPeriod: 168h
---
apiVersion: temporal.io/v1beta1
kind: TemporalCluster
metadata:
  name: temporal-cluster
  namespace: dgt-system
spec:
  version: 1.20.0
  numHistoryShards: 128
  persistence:
    defaultStore:
      sql:
        user: USERNAME
        pluginName: mysql
        databaseName: temporal
        connectAddr: ENDPOINT
        connectProtocol: tcp
      passwordSecretRef:
        name: mysql-creds-temporal
        key: PASSWORD
    visibilityStore:
      sql:
        user: USERNAME
        pluginName: mysql
        databaseName: temporal_visibility
        connectAddr: ENDPOINT
        connectProtocol: tcp
      passwordSecretRef:
        name: mysql-creds-temporal
        key: PASSWORD
  ui:
    enabled: true
  admintools:
    enabled: true
  metrics:
    enabled: false
```
The creds (username, pass, endpoint) are correct and the secret exists.

**Comment by alexandrevilain** [comment]
Thanks. I started looking at this issue.
Is the panic happening everytime it tries to reconcile the namespace ?

**Comment by DeluxeOwl** [comment]
No, it only happens sometimes.

I couldn't pinpoint at all what might cause this

**Comment by DeluxeOwl** [comment]
Indeed, they are submitted at the same time

**Comment by alexandrevilain** [comment]
Hi @DeluxeOwl ! 
I reopen this issue until you test the 1.13.3 which should fix your issue.
See : https://github.com/alexandrevilain/temporal-operator/releases/tag/v0.13.3

Let me know if everything is ok for your :)

**Comment by DeluxeOwl** [comment]
Everything works great, thanks for taking the time to fix the issue 😊
