### ISSUE TITLE
Unable to connect to cassandra hosted at another cluster.

### ISSUE THREAD

**Issue by debuggerpk** [alexandrevilain/temporal-operator#553]
Followed the instructions to run temporal operator with cassandra.

> We are already using cassandra for other tools and i just added a temporal keyspace to it

`temporal-cassandra-tool` works fine to create the temporal schema. I can also connect to cassandra using cqlsh.

```
 cassandra schema version compatibility check failed: gocql: unable to create session: unable to connect to initial hosts: host was filtered: 100.84.89.151
```

full logs

```
TEMPORAL_CLI_ADDRESS is not set, setting it to 100.73.0.152:7233
2023/11/12 15:54:11 Loading config; env=docker,zone=,configDir=config
2023/11/12 15:54:11 Loading config files=[config/docker.yaml]
{"level":"info","ts":"2023-11-12T15:54:11.740Z","msg":"Build info.","git-time":"2023-02-17T00:53:28.000Z","git-revision":"b313b7f586415f98dde332c6b4d1801e48b187a4","git-modified":false,"go-arch":"amd64","go-os":"linux","go-version":"go1.19.5","cgo-enabled":false,"server-version":"1.20.0","debug-mode":false,"logging-call-at":"main.go:143"}
{"level":"info","ts":"2023-11-12T15:54:11.740Z","msg":"Dynamic config client is not configured. Using noop client.","logging-call-at":"main.go:163"}
{"level":"warn","ts":"2023-11-12T15:54:11.740Z","msg":"Not using any authorizer and flag `--allow-no-auth` not detected. Future versions will require using the flag `--allow-no-auth` if you do not want to set an authorizer.","logging-call-at":"main.go:173"}
2023/11/12 15:54:11 gocql: unable setup control conn 100.84.89.151:9042: host was filtered: 100.84.89.151
[Fx] PROVIDE    *pprof.PProfInitializerImpl <= go.temporal.io/server/common/pprof.NewInitializer()
[Fx] PROVIDE    *temporal.ServerImpl <= go.temporal.io/server/temporal.NewServerFxImpl()
[Fx] PROVIDE    temporal.Server <= go.temporal.io/server/temporal.glob..func9()
[Fx] SUPPLY    []temporal.ServerOption
[Fx] PROVIDE    *temporal.serverOptions <= go.temporal.io/server/temporal.ServerOptionsProvider()
[Fx] PROVIDE    chan interface {} <= go.temporal.io/server/temporal.ServerOptionsProvider()
[Fx] PROVIDE    *config.Config <= go.temporal.io/server/temporal.ServerOptionsProvider()
[Fx] PROVIDE    *config.PProf <= go.temporal.io/server/temporal.ServerOptionsProvider()
[Fx] PROVIDE    log.Config <= go.temporal.io/server/temporal.ServerOptionsProvider()
[Fx] PROVIDE    resource.ServiceNames <= go.temporal.io/server/temporal.ServerOptionsProvider()
[Fx] PROVIDE    resource.NamespaceLogger <= go.temporal.io/server/temporal.ServerOptionsProvider()
[Fx] PROVIDE    resolver.ServiceResolver <= go.temporal.io/server/temporal.ServerOptionsProvider()
[Fx] PROVIDE    client.AbstractDataStoreFactory <= go.temporal.io/server/temporal.ServerOptionsProvider()
[Fx] PROVIDE    searchattribute.Mapper <= go.temporal.io/server/temporal.ServerOptionsProvider()
[Fx] PROVIDE    []grpc.UnaryServerInterceptor <= go.temporal.io/server/temporal.ServerOptionsProvider()
[Fx] PROVIDE    authorization.Authorizer <= go.temporal.io/server/temporal.ServerOptionsProvider()
[Fx] PROVIDE    authorization.ClaimMapper <= go.temporal.io/server/temporal.ServerOptionsProvider()
[Fx] PROVIDE    authorization.JWTAudienceMapper <= go.temporal.io/server/temporal.ServerOptionsProvider()
[Fx] PROVIDE    log.Logger <= go.temporal.io/server/temporal.ServerOptionsProvider()
[Fx] PROVIDE    client.FactoryProvider <= go.temporal.io/server/temporal.ServerOptionsProvider()
[Fx] PROVIDE    dynamicconfig.Client <= go.temporal.io/server/temporal.ServerOptionsProvider()
[Fx] PROVIDE    *dynamicconfig.Collection <= go.temporal.io/server/temporal.ServerOptionsProvider()
[Fx] PROVIDE    encryption.TLSConfigProvider <= go.temporal.io/server/temporal.ServerOptionsProvider()
[Fx] PROVIDE    *client.Config <= go.temporal.io/server/temporal.ServerOptionsProvider()
[Fx] PROVIDE    client.Client <= go.temporal.io/server/temporal.ServerOptionsProvider()
[Fx] PROVIDE    metrics.Handler <= go.temporal.io/server/temporal.ServerOptionsProvider()
[Fx] PROVIDE    []trace.SpanExporter <= go.temporal.io/server/temporal.glob..func2()
[Fx] PROVIDE    client.FactoryProviderFn <= go.temporal.io/server/temporal.PersistenceFactoryProvider()
[Fx] PROVIDE    *temporal.ServicesMetadata[group = "services"] <= go.temporal.io/server/temporal.HistoryServiceProvider()
[Fx] PROVIDE    *temporal.ServicesMetadata[group = "services"] <= go.temporal.io/server/temporal.MatchingServiceProvider()
[Fx] PROVIDE    *temporal.ServicesMetadata[group = "services"] <= go.temporal.io/server/temporal.FrontendServiceProvider()
[Fx] PROVIDE    *temporal.ServicesMetadata[group = "services"] <= go.temporal.io/server/temporal.InternalFrontendServiceProvider()
[Fx] PROVIDE    *temporal.ServicesMetadata[group = "services"] <= go.temporal.io/server/temporal.WorkerServiceProvider()
[Fx] PROVIDE    *cluster.Config <= go.temporal.io/server/temporal.ApplyClusterMetadataConfigProvider()
[Fx] PROVIDE    config.Persistence <= go.temporal.io/server/temporal.ApplyClusterMetadataConfigProvider()
[Fx] PROVIDE    fx.Lifecycle <= go.uber.org/fx.New.func1()
[Fx] PROVIDE    fx.Shutdowner <= go.uber.org/fx.(*App).shutdowner-fm()
[Fx] PROVIDE    fx.DotGraph <= go.uber.org/fx.(*App).dotGraph-fm()
[Fx] ERROR        Failed to initialize custom logger: could not build arguments for function "go.uber.org/fx".(*App).constructCustomLogger.func2
    /go/pkg/mod/go.uber.org/fx@v1.18.2/app.go:414:
failed to build fxevent.Logger:
could not build arguments for function "go.temporal.io/server/temporal".glob..func8
    /home/builder/temporal/temporal/fx.go:1013:
failed to build log.Logger:
received non-nil error from function "go.temporal.io/server/temporal".ServerOptionsProvider
    /home/builder/temporal/temporal/fx.go:159:
cassandra schema version compatibility check failed: gocql: unable to create session: unable to connect to initial hosts: host was filtered: 100.84.89.151
Unable to create server. Error: could not build arguments for function "go.uber.org/fx".(*App).constructCustomLogger.func2 (/go/pkg/mod/go.uber.org/fx@v1.18.2/app.go:414): failed to build fxevent.Logger: could not build arguments for function "go.temporal.io/server/temporal".glob..func8 (/home/builder/temporal/temporal/fx.go:1013): failed to build log.Logger: received non-nil error from function "go.temporal.io/server/temporal".ServerOptionsProvider (/home/builder/temporal/temporal/fx.go:159): cassandra schema version compatibility check failed: gocql: unable to create session: unable to connect to initial hosts: host was filtered: 100.84.89.151.
Stream closed EOF for temporal/shared-worker-f787bf96f-6qr7q (service)

```

versions

operator: 0.15.4
temporal: 1.20.4

**Comment by alexandrevilain** [comment]
Hi! 

Could you please provide your configuration ?

Did you set the datacenter configuration ? Looks like temporal only creates a filter is the `datacenter` was set (see: https://github.com/temporalio/temporal/blob/main/common/persistence/nosql/nosqlplugin/cassandra/gocql/client.go#L81C37-L81C37)

**Comment by debuggerpk** [comment]
thanks @alexandrevilain for the quick reply.

```yaml
apiVersion: temporal.io/v1beta1
kind: TemporalCluster
metadata:
  name: shared
  namespace: temporal
spec:
  log: 
    level: debug
  version: 1.20.0
  numHistoryShards: 1
  jobTtlSecondsAfterFinished: 300
  persistence:
    defaultStore:
      cassandra:
        hosts:
          - shared-v1-client.cass
        port: 9042
        maxConns: 50
        connectTimeout: 10s
        user: temporal_app_client
        keyspace: temporal
        datacenter: vendors-gke
        disableInitialHostLookup: true
      passwordSecretRef:
        name: cassandra-password
        key: PASSWORD
      skipCreate: true
    visibilityStore:
      cassandra:
        hosts:
          - shared-v1-client.cass
        port: 9042
        user: temporal_app_client
        keyspace: temporal_visibility
        datacenter: vendors-gke
        disableInitialHostLookup: true
      passwordSecretRef:
        name: cassandra-password
        key: PASSWORD
      skipCreate: true
```

just to check if i was doing something wrong, i wrote a small go program quickly check if it is a problem with `gocql`. The said binary was compiled with `-tags gocql_debug`
```go
package main

import (
	"log/slog"

	"github.com/gocql/gocql"
)

func main() {
	cluster := gocql.NewCluster("10.10.0.5")

	cluster.Keyspace = "temporal"
	cluster.PoolConfig.HostSelectionPolicy = gocql.TokenAwareHostPolicy(gocql.DCAwareRoundRobinPolicy("gke-vendors"))
	cluster.Authenticator = gocql.PasswordAuthenticator{
		Username: "temporal_app_client",
		Password: "redacted",
	}
	cluster.DisableInitialHostLookup = true

	slog.Info("cluster", slog.Any("cluster", cluster))

	session, err := cluster.CreateSession()
	if err != nil {
		slog.Error("error", slog.Any("err", err))
	}

	defer session.Close()

	count := -1

	if err := session.Query("SELECT count(*) FROM namespaces").Scan(&count); err != nil {
		slog.Error("error", slog.Any("err", err))
	}

	slog.Info("count", slog.Any("count", count))

	slog.Info("session", slog.Any("session", session))
}
```

The output of the program can be found at

```log
2023/11/12 17:34:54 INFO cluster cluster="&{Hosts:[10.10.0.5] CQLVersion:3.0.0 ProtoVersion:0 Timeout:11s ConnectTimeout:11s WriteTimeout:0s Port:9042 Keyspace:temporal NumConns:2 Consistency:QUORUM Compressor:<nil> Authenticator:{Username:temporal_app_client Password:7fb1jVdqE2NnxqffyCV7VkMu AllowedAuthenticators:[]} AuthProvider:<nil> RetryPolicy:<nil> ConvictionPolicy:0x9177a0 ReconnectionPolicy:0xc00009c220 SocketKeepalive:0s MaxPreparedStmts:1000 MaxRoutingKeyInfo:1000 PageSize:5000 SerialConsistency:UNKNOWN_SERIAL_CONS_0x0 SslOpts:<nil> DefaultTimestamp:true PoolConfig:{HostSelectionPolicy:0xc0000ce280} ReconnectInterval:1m0s MaxWaitSchemaAgreement:1m0s HostFilter:<nil> AddressTranslator:<nil> IgnorePeerAddr:false DisableInitialHostLookup:true Events:{DisableNodeStatusEvents:false DisableTopologyEvents:false DisableSchemaEvents:false} DisableSkipMetadata:false QueryObserver:<nil> BatchObserver:<nil> ConnectObserver:<nil> FrameHeaderObserver:<nil> StreamObserver:<nil> DefaultIdempotence:false WriteCoalesceWaitTime:200µs Dialer:<nil> HostDialer:<nil> Logger:<nil> disableControlConn:false}"
2023/11/12 17:34:54 control: error executing "\n\t\tSELECT durable_writes, strategy_class, strategy_options\n\t\tFROM system.schema_keyspaces\n\t\tWHERE keyspace_name = ?": unconfigured table schema_keyspaces
2023/11/12 17:34:54 control: error executing "\n\t\tSELECT durable_writes, strategy_class, strategy_options\n\t\tFROM system.schema_keyspaces\n\t\tWHERE keyspace_name = ?": unconfigured table schema_keyspaces
2023/11/12 17:34:54 control: error executing "\n\t\tSELECT durable_writes, strategy_class, strategy_options\n\t\tFROM system.schema_keyspaces\n\t\tWHERE keyspace_name = ?": unconfigured table schema_keyspaces
2023/11/12 17:34:54 control: error executing "\n\t\tSELECT durable_writes, strategy_class, strategy_options\n\t\tFROM system.schema_keyspaces\n\t\tWHERE keyspace_name = ?": unconfigured table schema_keyspaces
2023/11/12 17:34:54 gocql: Session.handleNodeConnected: 10.10.0.5:9042
2023/11/12 17:34:54 gocql: conns of pool after stopped "10.10.0.5": 2
2023/11/12 17:34:54 INFO count count=0
2023/11/12 17:34:54 INFO session session="&{cons:4 pageSize:5000 prefetch:0.25 routingKeyInfoCache:{lru:0xc0000b2c20 mu:{state:0 sema:0}} schemaDescriber:0xc0000980d8 trace:<nil> queryObserver:<nil> batchObserver:<nil> connectObserver:<nil> frameObserver:<nil> streamObserver:<nil> hostSource:0xc0000a0380 ringRefresher:0xc0000a03c0 stmtsLRU:0xc0000841e0 connCfg:0xc000094460 executor:0xc000098138 pool:0xc000080320 policy:0xc0000ce280 ring:{endpoints:[0xc0000fe000] mu:{w:{state:0 sema:0} writerSem:0 readerSem:0 readerCount:{_:{} v:0} readerWait:{_:{} v:0}} hosts:map[0c181686-b85d-46d1-8e84-30450e271c86:0xc0000fe000 317527c7-b3eb-4756-8d52-6efc4881026a:0xc0000fe180] hostIPToUUID:map[0.0.0.0:0c181686-b85d-46d1-8e84-30450e271c86 100.84.103.99:317527c7-b3eb-4756-8d52-6efc4881026a] hostList:[0xc0000fe180 0xc0000fe000] pos:0} metadata:{mu:{w:{state:0 sema:0} writerSem:0 readerSem:0 readerCount:{_:{} v:0} readerWait:{_:{} v:0}} partitioner:} mu:{w:{state:0 sema:0} writerSem:0 readerSem:0 readerCount:{_:{} v:0} readerWait:{_:{} v:0}} control:0xc0000a0400 nodeEvents:0xc00009e180 schemaEvents:0xc00009e240 useSystemSchema:true hasAggregatesAndFunctions:false cfg:{Hosts:[10.10.0.5] CQLVersion:3.0.0 ProtoVersion:4 Timeout:11000000000 ConnectTimeout:11000000000 WriteTimeout:0 Port:9042 Keyspace:temporal NumConns:2 Consistency:4 Compressor:<nil> Authenticator:{Username:temporal_app_client Password:7fb1jVdqE2NnxqffyCV7VkMu AllowedAuthenticators:[]} AuthProvider:<nil> RetryPolicy:<nil> ConvictionPolicy:0x9177a0 ReconnectionPolicy:0xc00009c220 SocketKeepalive:0 MaxPreparedStmts:1000 MaxRoutingKeyInfo:1000 PageSize:5000 SerialConsistency:0 SslOpts:<nil> DefaultTimestamp:true PoolConfig:{HostSelectionPolicy:0xc0000ce280} ReconnectInterval:60000000000 MaxWaitSchemaAgreement:60000000000 HostFilter:<nil> AddressTranslator:<nil> IgnorePeerAddr:false DisableInitialHostLookup:true Events:{DisableNodeStatusEvents:false DisableTopologyEvents:false DisableSchemaEvents:false} DisableSkipMetadata:false QueryObserver:<nil> BatchObserver:<nil> ConnectObserver:<nil> FrameHeaderObserver:<nil> StreamObserver:<nil> DefaultIdempotence:false WriteCoalesceWaitTime:200000 Dialer:<nil> HostDialer:<nil> Logger:<nil> disableControlConn:false} ctx:0xc0000801e0 cancel:0x4c1700 sessionStateMu:{w:{state:0 sema:0} writerSem:0 readerSem:0 readerCount:{_:{} v:0} readerWait:{_:{} v:0}} isClosed:false isClosing:false isInitialized:true logger:0x9177a0}"
```

**Comment by alexandrevilain** [comment]
What's the IP returned by the error `host was filtered: 100.84.89.151` ?

**Comment by debuggerpk** [comment]
how to check that ?

**Comment by debuggerpk** [comment]
my cluster ip is "100.84.89.151" while the pod id is "100.73.0.152"

**Comment by debuggerpk** [comment]
More Info, I download the temporal binary on a vm. setup my temporal's development.yaml to

```yaml
log:
  stdout: true
  level: info

persistence:
  defaultStore: cass-default
  visibilityStore: cass-visibility
  numHistoryShards: 4
  datastores:
    cass-default:
      cassandra:
        user: "temporal_app_client"
        password: "redacted"
        hosts: "10.10.0.5"
        disableInitialHostLookup: true
        keyspace: "temporal"
    cass-visibility:
      cassandra:
        user: "temporal_app_client"
        password: "redacted"
        hosts: "10.10.0.5"
        keyspace: "temporal_visibility"
        disableInitialHostLookup: true
global:
  membership:
    maxJoinDuration: 30s
    broadcastAddress: "127.0.0.1"
  pprof:
    port: 7936
  metrics:
    prometheus:
#      # specify framework to use new approach for initializing metrics and/or use opentelemetry
#      framework: "opentelemetry"
      framework: "tally"
      timerType: "histogram"
      listenAddress: "127.0.0.1:8000"
#    # Deprecated
#    prometheusSDK:
#      framework: "tally"
#      timerType: "histogram"
#      listenAddress: "127.0.0.1:8001"
#    tags:
#      type: test
#    excludeTags:
#      namespace:
#        - temporal-system
#    perUnitHistogramBoundaries:
#      dimensionless:
#        - 10
#        - 100
#        - 1000
#      milliseconds:
#        - 10
#        - 100
#        - 1000
#        - 60000
#      bytes:
#        - 1024
#        - 1048576
#        - 1073741824

services:
  frontend:
    rpc:
      grpcPort: 7233
      membershipPort: 6933
      bindOnLocalHost: true
      httpPort: 7243

  matching:
    rpc:
      grpcPort: 7235
      membershipPort: 6935
      bindOnLocalHost: true

  history:
    rpc:
      grpcPort: 7234
      membershipPort: 6934
      bindOnLocalHost: true

  worker:
    rpc:
      grpcPort: 7239
      membershipPort: 6939
      bindOnLocalHost: true

clusterMetadata:
  enableGlobalNamespace: false
  failoverVersionIncrement: 10
  masterClusterName: "active"
  currentClusterName: "active"
  clusterInformation:
    active:
      enabled: true
      initialFailoverVersion: 1
      rpcName: "frontend"
      rpcAddress: "localhost:7233"

dcRedirectionPolicy:
  policy: "noop"

archival:
  history:
    state: "enabled"
    enableRead: true
    provider:
      filestore:
        fileMode: "0666"
        dirMode: "0766"
      gstorage:
        credentialsPath: "/tmp/gcloud/keyfile.json"
  visibility:
    state: "enabled"
    enableRead: true
    provider:
      filestore:
        fileMode: "0666"
        dirMode: "0766"

namespaceDefaults:
  archival:
    history:
      state: "disabled"
      URI: "file:///tmp/temporal_archival/development"
    visibility:
      state: "disabled"
      URI: "file:///tmp/temporal_vis_archival/development"

dynamicConfigClient:
  filepath: "./config/dynamicconfig/development-cass.yaml"
  pollInterval: "10s"
```

the temporal server was able to connect to the service quickly.

PS: i have created a network load balancer on top of cassandra thus the different ip.

**Comment by debuggerpk** [comment]
This appears to be a gocql driver issue, after replicating https://github.com/temporalio/temporal/blob/82f103d38eaf317a078a00f812e3e792683c097f/common/persistence/nosql/nosqlplugin/cassandra/gocql/client.go#L81

in my program

```go
	cluster.ProtoVersion = 4
	cluster.PoolConfig.HostSelectionPolicy = gocql.TokenAwareHostPolicy(gocql.DCAwareRoundRobinPolicy(datacenter))
	cluster.HostFilter = gocql.DataCentreHostFilter(datacenter)
```

I am able to replicate the issue

```log
goroutine 1 [running]:
github.com/gocql/gocql.(*Session).Close(0x0)
	/Users/jay/go/pkg/mod/github.com/gocql/gocql@v1.6.0/session.go:469 +0x17
panic({0x1297800?, 0x14e8800?})
	/usr/local/opt/go/libexec/src/runtime/panic.go:914 +0x21f
github.com/gocql/gocql.(*Query).defaultsFromSession(0xc0000a4280)
	/Users/jay/go/pkg/mod/github.com/gocql/gocql@v1.6.0/session.go:933 +0x28
github.com/gocql/gocql.(*Session).Query(0x0, {0x12e7d26, 0x1f}, {0x0, 0x0, 0x0})
	/Users/jay/go/pkg/mod/github.com/gocql/gocql@v1.6.0/session.go:439 +0xf9
main.main()
	/Users/jay/Work/cluster-test/main.go:35 +0x5f8
exit status 2
```

which appears to be at the following piece of code

```
func (s *Session) Close() {
	s.sessionStateMu.Lock()
	if s.isClosing {
		s.sessionStateMu.Unlock()
		return
	}
```

can i suggest making the datacenter property optional for the time being until we can figure out the root of the issue?

**Comment by alexandrevilain** [comment]
> Can i suggest making the datacenter property optional for the time being until we can figure out the root of the issue?

For sure ! Would you like to propose a Pull Request ?

**Comment by debuggerpk** [comment]
> > Can i suggest making the datacenter property optional for the time being until we can figure out the root of the issue?
> 
> For sure ! Would you like to propose a Pull Request ?

Let me take a crack at it.

On a side note. Figured out the root cause of the issue. it appears at https://github.com/gocql/gocql/blob/34fdeebefcbf183ed7f916f931aa0586fdaa1b40/ring.go#L95 when the server tries to add to add my load-balancer ip which i am connecting to any of the ip provided by cassandra pods.

see the screenshot.

<img width="509" alt="Screen Shot 2023-11-15 at 1 46 33 PM" src="https://github.com/alexandrevilain/temporal-operator/assets/1317783/4af2f621-b2ce-4168-8c41-ab0b86ab01d6">
