### ISSUE TITLE
operator panic after upgrade to v0.16.0 due to missing service httpPort

### ISSUE THREAD

**Issue by plaisted** [alexandrevilain/temporal-operator#560]
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]                                                 │
│     panic: runtime error: invalid memory address or nil pointer dereference                                                         │
│ [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1fcdebc]                                                             │
│                                                                                                                                     │
│ goroutine 342 [running]:                                                                                                            │
│ sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()                                              │
│     /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/internal/controller/controller.go:115 +0x1fa                             │
│ panic({0x22f1860, 0x400b6f0})                                                                                                       │
│     /usr/local/go/src/runtime/panic.go:884 +0x213                                                                                   │
│ github.com/alexandrevilain/temporal-operator/internal/resource/config.(*ConfigmapBuilder).Update(0xc001b6a430, {0x2c25708?, 0xc0019 │
│     /workspace/internal/resource/config/configmap_builder.go:243 +0x3fc                                                             │
│ github.com/alexandrevilain/controller-tools/pkg/reconciler.(*Reconciler).ReconcileBuilder.func1()                                   │
│     /go/pkg/mod/github.com/alexandrevilain/controller-tools@v0.2.2/pkg/reconciler/reconciler.go:54 +0x2a                            │
│ sigs.k8s.io/controller-runtime/pkg/controller/controllerutil.mutate(0xc001913320?, {{0xc000ddec50?, 0x0?}, {0xc001b5f230?, 0x2c08d9 │
│     /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/controller/controllerutil/controllerutil.go:339 +0x4f                    │
│ sigs.k8s.io/controller-runtime/pkg/controller/controllerutil.CreateOrUpdate({0x2c08d98, 0xc000b80f00}, {0x2c15c60, 0xc000154d80}, { │
│     /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/controller/controllerutil/controllerutil.go:211 +0x274                   │
│ github.com/alexandrevilain/controller-tools/pkg/reconciler.(*Reconciler).ReconcileBuilder(0xc00097c240, {0x2c08d98, 0xc000b80f00},  │
│     /go/pkg/mod/github.com/alexandrevilain/controller-tools@v0.2.2/pkg/reconciler/reconciler.go:53 +0x115                           │
│ github.com/alexandrevilain/temporal-operator/controllers.(*TemporalClusterReconciler).reconcileResources(0xc00097c280, {0x2c08d98,  │
│     /workspace/controllers/temporalcluster_controller.go:153 +0xe5                                                                  │
│ github.com/alexandrevilain/temporal-operator/controllers.(*TemporalClusterReconciler).Reconcile(0xc00097c280, {0x2c08d98, 0xc000b80 │
│     /workspace/controllers/temporalcluster_controller.go:143 +0x73a                                                                 │
│ sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x2c08d98?, {0x2c08d98?, 0xc000b80f00?}, {{{0xc000a8 │
│     /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/internal/controller/controller.go:118 +0xc8                              │
│ sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000950aa0, {0x2c08cf0, 0xc00085d450}, {0x2 │
│     /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/internal/controller/controller.go:314 +0x377                             │
│ sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000950aa0, {0x2c08cf0, 0xc00085d450})   │
│     /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/internal/controller/controller.go:265 +0x1d9                             │
│ sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()                                                │
│     /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/internal/controller/controller.go:226 +0x85                              │
│ created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2                                         │
│     /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/internal/controller/controller.go:222 +0x587                             │
│ Stream closed EOF for temporal-system/temporal-operator-controller-manager-7884cdc974-wkmbs (manager)                               │
│
```

Downgrading to previously used v0.15.3 resolved the issue. Is there an upgrade step I missed or is this a bug?

**Comment by plaisted** [comment]
This appears to be due to the added field 'httpPort' on services resulting in a panic on reconciliation. I was able to get around this by forcing an edit before reconciliation ran with the new operator version. The edit ran the operator webhook which replaces missing values with their defaults fixing the issue with the missing field / panic on reconciliation.

This was somewhat tricky to do as the operator has to be running to accept temporalcluster CRD changes (or else they'll get rejected with `no endpoints available for service "temporal-operator-webhook-service"` but has to occur before the operator has started reconciliation and hits the panic.

**Comment by alexandrevilain** [comment]
Hi @plaisted !
Thanks for reporting the issue. I think that the best pratice is to test for nil value for a variable *where it is used*, so I'll fix that asap!

**Comment by Aoao54** [comment]
Hi @alexandrevilain , if there is a hot fix release plan about it? We have the same issue when upgrading temporal-operator : )
